# Generated by Django 3.2.6 on 2021-08-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210813_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='deleted_at',
        ),
    ]
