# Generated by Django 3.2.6 on 2021-08-13 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210808_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
