# Generated by Django 3.2.6 on 2021-08-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='diameter',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
